#!/bin/bash

read -r -p 'Commit message: ' commitMsg  # prompt user for commit message

if [ $commitMsg -z ]
then 
    echo You did not enter a commit message, please enter a message.
    read -r -p 'Commit message: ' commitMsg 
else 
    true
fi

git add .
echo adding all files...

git commit -m "$commitMsg"
echo comitting w/message...

git push origin master
echo pushing to github...